export interface EmergencyContact {
  id: number
  name: string
  region: string
  type: "hospital" | "rescue" | "emergency" | string
  phone: string
  address: string
  hours: string
  notes?: string
  services: string[]
}
const  EmergencyContactsData :  EmergencyContact[] = [
  // Yangon Region
  {
    id: 1,
    name: "Yangon General Hospital",
    type: "hospital",
    phone: "01-256112",
    address: "Bogyoke Aung San Rd, Yangon",
    region: "Yangon",
    hours: "24/7 Emergency",
    services: ["Trauma", "ICU", "Ambulance", "Surgery"],
    notes: "Main public hospital with full emergency services",
  },
  {
    id: 2,
    name: "Pun Hlaing Hospital",
    type: "hospital",
    phone: "01-650766",
    address: "Hlaing Township, Yangon",
    region: "Yangon",
    hours: "24/7",
    services: ["Private Care", "ICU", "Emergency"],
    notes: "Premium private hospital",
  },
  {
    id: 3,
    name: "Yangon Fire Department",
    type: "rescue",
    phone: "01-395555",
    address: "Sule Pagoda Rd, Yangon",
    region: "Yangon",
    hours: "24/7",
    services: ["Fire", "Rescue", "Emergency"],
    notes: "Main fire station",
  },
  // Mandalay Region
  {
    id: 4,
    name: "Mandalay General Hospital",
    type: "hospital",
    phone: "02-65391",
    address: "30th St, Mandalay",
    region: "Mandalay",
    hours: "24/7 Emergency",
    services: ["Trauma", "Surgery", "ICU"],
    notes: "Regional referral hospital",
  },
  {
    id: 5,
    name: "Mandalay Rescue Team",
    type: "rescue",
    phone: "02-654321",
    address: "78th St, Mandalay",
    region: "Mandalay",
    hours: "6:00 AM - 10:00 PM",
    services: ["Fire", "Flood", "First Aid"],
    notes: "Volunteer rescue team",
  },
  {
    id: 6,
    name: "Shwe Thanlwin Hospital",
    type: "hospital",
    phone: "02-61234",
    address: "35th St, Mandalay",
    region: "Mandalay",
    hours: "24/7",
    services: ["General", "Maternity", "Pediatrics"],
    notes: "Private hospital",
  },
  // Nay Pyi Taw
  {
    id: 7,
    name: "Nay Pyi Taw Emergency Center",
    type: "emergency",
    phone: "067-123456",
    address: "Ottara Thiri Township",
    region: "Nay Pyi Taw",
    hours: "24/7",
    services: ["Police", "Ambulance", "Fire"],
    notes: "Central emergency coordination",
  },
  {
    id: 8,
    name: "Nay Pyi Taw Hospital",
    type: "hospital",
    phone: "067-234567",
    address: "Zabuthiri Township",
    region: "Nay Pyi Taw",
    hours: "24/7",
    services: ["General", "Emergency", "ICU"],
    notes: "Government hospital",
  },
  // Shan State
  {
    id: 9,
    name: "Taunggyi General Hospital",
    type: "hospital",
    phone: "081-21234",
    address: "Taunggyi, Shan State",
    region: "Shan",
    hours: "24/7 Emergency",
    services: ["General", "Pediatrics", "Surgery"],
    notes: "Main hospital for Shan State",
  },
  {
    id: 10,
    name: "Lashio District Hospital",
    type: "hospital",
    phone: "082-22345",
    address: "Lashio, Shan State",
    region: "Shan",
    hours: "8:00 AM - 8:00 PM",
    services: ["General", "Emergency"],
    notes: "District level hospital",
  },
  // Kachin State
  {
    id: 11,
    name: "Myitkyina General Hospital",
    type: "hospital",
    phone: "074-23456",
    address: "Myitkyina, Kachin State",
    region: "Kachin",
    hours: "24/7",
    services: ["Trauma", "General", "Maternity"],
    notes: "State capital hospital",
  },
  {
    id: 12,
    name: "Kachin Rescue Service",
    type: "rescue",
    phone: "074-34567",
    address: "Myitkyina, Kachin State",
    region: "Kachin",
    hours: "24/7",
    services: ["Mountain Rescue", "Flood", "Emergency"],
    notes: "Specialized mountain rescue",
  },
  // Kayah State
  {
    id: 13,
    name: "Loikaw General Hospital",
    type: "hospital",
    phone: "083-21234",
    address: "Loikaw, Kayah State",
    region: "Kayah",
    hours: "24/7",
    services: ["General", "Emergency"],
    notes: "State hospital",
  },
  // Kayin State
  {
    id: 14,
    name: "Hpa-an General Hospital",
    type: "hospital",
    phone: "058-21234",
    address: "Hpa-an, Kayin State",
    region: "Kayin",
    hours: "24/7",
    services: ["General", "Maternity", "Emergency"],
    notes: "State capital hospital",
  },
  {
    id: 15,
    name: "Kayin Emergency Response",
    type: "emergency",
    phone: "058-23456",
    address: "Hpa-an, Kayin State",
    region: "Kayin",
    hours: "24/7",
    services: ["Police", "Fire", "Medical"],
    notes: "State emergency services",
  },
  // Chin State
  {
    id: 16,
    name: "Hakha General Hospital",
    type: "hospital",
    phone: "070-21234",
    address: "Hakha, Chin State",
    region: "Chin",
    hours: "8:00 AM - 6:00 PM",
    services: ["General", "Basic Emergency"],
    notes: "Remote area hospital",
  },
  // Mon State
  {
    id: 17,
    name: "Mawlamyine General Hospital",
    type: "hospital",
    phone: "057-21234",
    address: "Mawlamyine, Mon State",
    region: "Mon",
    hours: "24/7",
    services: ["General", "Surgery", "ICU"],
    notes: "Regional hospital",
  },
  {
    id: 18,
    name: "Mon State Fire Department",
    type: "rescue",
    phone: "057-23456",
    address: "Mawlamyine, Mon State",
    region: "Mon",
    hours: "24/7",
    services: ["Fire", "Rescue", "Emergency"],
    notes: "State fire services",
  },
  // Rakhine State
  {
    id: 19,
    name: "Sittwe General Hospital",
    type: "hospital",
    phone: "043-21234",
    address: "Sittwe, Rakhine State",
    region: "Rakhine",
    hours: "24/7",
    services: ["General", "Emergency", "Maternity"],
    notes: "Coastal region hospital",
  },
  {
    id: 20,
    name: "Rakhine Coast Guard",
    type: "rescue",
    phone: "043-23456",
    address: "Sittwe Port, Rakhine State",
    region: "Rakhine",
    hours: "24/7",
    services: ["Marine Rescue", "Emergency"],
    notes: "Maritime emergency services",
  },
  // Bago Region
  {
    id: 21,
    name: "Bago General Hospital",
    type: "hospital",
    phone: "052-21234",
    address: "Bago City, Bago Region",
    region: "Bago",
    hours: "24/7",
    services: ["General", "Surgery", "Emergency"],
    notes: "Regional referral center",
  },
  {
    id: 22,
    name: "Pyay District Hospital",
    type: "hospital",
    phone: "053-21234",
    address: "Pyay, Bago Region",
    region: "Bago",
    hours: "24/7",
    services: ["General", "Maternity"],
    notes: "District hospital",
  },
  // Magway Region
  {
    id: 23,
    name: "Magway General Hospital",
    type: "hospital",
    phone: "063-21234",
    address: "Magway City, Magway Region",
    region: "Magway",
    hours: "24/7",
    services: ["General", "Emergency"],
    notes: "Regional hospital",
  },
  {
    id: 24,
    name: "Pakokku Hospital",
    type: "hospital",
    phone: "062-21234",
    address: "Pakokku, Magway Region",
    region: "Magway",
    hours: "8:00 AM - 8:00 PM",
    services: ["General", "Basic Emergency"],
    notes: "District hospital",
  },
  // Sagaing Region
  {
    id: 25,
    name: "Sagaing General Hospital",
    type: "hospital",
    phone: "071-21234",
    address: "Sagaing City, Sagaing Region",
    region: "Sagaing",
    hours: "24/7",
    services: ["General", "Surgery", "ICU"],
    notes: "Regional hospital",
  },
  {
    id: 26,
    name: "Monywa District Hospital",
    type: "hospital",
    phone: "071-23456",
    address: "Monywa, Sagaing Region",
    region: "Sagaing",
    hours: "24/7",
    services: ["General", "Emergency"],
    notes: "District level care",
  },
  // Tanintharyi Region
  {
    id: 27,
    name: "Myeik General Hospital",
    type: "hospital",
    phone: "059-21234",
    address: "Myeik, Tanintharyi Region",
    region: "Tanintharyi",
    hours: "24/7",
    services: ["General", "Surgery", "Maternity"],
    notes: "Southern region hospital",
  },
  {
    id: 28,
    name: "Dawei District Hospital",
    type: "hospital",
    phone: "059-23456",
    address: "Dawei, Tanintharyi Region",
    region: "Tanintharyi",
    hours: "24/7",
    services: ["General", "Emergency"],
    notes: "Coastal district hospital",
  },
  // Ayeyarwady Region
  {
    id: 29,
    name: "Pathein General Hospital",
    type: "hospital",
    phone: "042-21234",
    address: "Pathein, Ayeyarwady Region",
    region: "Ayeyarwady",
    hours: "24/7",
    services: ["General", "Surgery", "ICU"],
    notes: "Delta region hospital",
  },
  {
    id: 30,
    name: "Ayeyarwady River Rescue",
    type: "rescue",
    phone: "042-23456",
    address: "Pathein Port, Ayeyarwady Region",
    region: "Ayeyarwady",
    hours: "24/7",
    services: ["Water Rescue", "Flood Response"],
    notes: "River and flood emergency services",
  },
  // National emergency services
  {
    id: 31,
    name: "National Emergency Hotline",
    type: "emergency",
    phone: "999",
    address: "Nationwide Service",
    region: "National",
    hours: "24/7",
    services: ["Police", "Fire", "Medical", "Rescue"],
    notes: "National emergency coordination center",
  },
  {
    id: 32,
    name: "Myanmar Red Cross",
    type: "rescue",
    phone: "01-370153",
    address: "42 Strand Rd, Yangon",
    region: "National",
    hours: "24/7",
    services: ["Disaster Relief", "First Aid", "Blood Bank"],
    notes: "International humanitarian organization",
  },
  {
    id: 33,
    name: "Police Hotline",
    type: "emergency",
    phone: "199",
    address: "Nationwide Service",
    region: "National",
    hours: "24/7",
    services: ["Police", "Crime Reporting"],
    notes: "National police emergency hotline",
  },
  {
    id: 34,
    name: "Ambulance Service",
    type: "emergency",
    phone: "192",
    address: "Nationwide Service",
    region: "National",
    hours: "24/7",
    services: ["Medical Emergency", "Ambulance Dispatch"],
    notes: "National ambulance emergency hotline",
  },
  {
    id: 35,
    name: "Fire Service",
    type: "emergency",
    phone: "191",
    address: "Nationwide Service",
    region: "National",
    hours: "24/7",
    services: ["Fire Emergency", "Rescue"],
    notes: "National fire emergency hotline",
  },
]

export default EmergencyContactsData;